### ISSUE TITLE
How fetching 1 million+ apps is possible using this crawler ? 

### ISSUE THREAD

**Issue by keith4u** [MarcelloLins/GooglePlayAppsCrawler#10]
how can we get all the apps of google playstore using this as I can see we are querying the playstore only for 26 alphabets  [A-Z] & category-names. Please see the snapshot for details.

![crawler](https://cloud.githubusercontent.com/assets/9844090/5938828/9dd4dd44-a724-11e4-8db3-ed32ebb32b2d.png)

**Comment by MarcelloLins** [comment]
Hello Keith 4 U.

Please, refer to the Wiki documentation of this project if you have any questions.

https://github.com/MarcelloLins/GooglePlayAppsCrawler/wiki/Project-Architecture

One way or another, let me try to makes things clearer for you.

This initial search for 26 characters [A-Z] and some categories is used to 'Bootstrap' / 'Kickstart' the database, serving as a way to populate it with an initial sample of apps. 

Since "Google Play Store" doesn't allow for simply paging through all the results of a search, until there are no more results, I've had to come up with my own solution to increase reach further than this initial sample of apps.

In order to increase the Crawler's reach you have to fire the "Workers", which will basically use the apps on the database already, to reach more apps (using the "Similar apps" and "More from Developer" sections of each app page). 

The documentation presents a "step-by-step" example of what exactly is being executed, in which order, by the workers.

I hope this makes your life easier.

**Comment by keith4u** [comment]
Thanks for the support MarcelloLins !!
Is there any PHP port of this project ??
