### ISSUE TITLE
Crawler should ensure a unique index on URL

### ISSUE THREAD

**Issue by seiyria** [MarcelloLins/GooglePlayAppsCrawler#26]
This way if you run the crawler multiple times, you don't get a bunch of extra garbage data. In fact, there probably should be at least one unique index (compound or otherwise) in each project to prevent this from happening.

**Comment by MarcelloLins** [comment]
Yes. I"ve done this with the Python version. All we would have to change is to make the "url" the actual "_id" field, instead of having mongoDB generate its own ObjectID value for this field.

The one constraint that MongoDB ensures out of the box is the uniqueness of the "ID" field (which can be "ID", "id" "Id" or "_id").

If we make _id = url we won't have to create the index for it before hand, since this is the only built-in index on MongoDB

**Comment by seiyria** [comment]
You don't have to change the id field or anything, you can just add another unique index (see [here](http://docs.mongodb.org/manual/tutorial/create-a-unique-index/)). 

Just add that to your guide and your ensureIndex calls.

**Comment by MarcelloLins** [comment]
Yep. Or that :)

Will do ! TYVM !

**Comment by seiyria** [comment]
Yes, of course. Thank you! I realized this was a problem after I ran the Crawler about 6 times and my collection size was a bit larger than it needed to be.
