### ISSUE TITLE
ReviewWorker stops processing

### ISSUE THREAD

**Issue by seiyria** [MarcelloLins/GooglePlayAppsCrawler#35]
So, suppose the ReviewWorker is working on a separate server from the PlayStoreWorker - this means the ReviewWorker is processing data a lot faster than the PlayStoreWorker can.

What sorts of things do you do in a situation like this? It's bad to make the ReviewWorker wait because you might be at the end of apps to process, but at the same time... 

I think the best solution might be to spin up servers with 1 PlayStoreWorker and 1 ReviewWorker and just make the ReviewWorker run every 10 minutes, which should give it plenty to do, but I'm open to hearing ideas as well!

**Comment by MarcelloLins** [comment]
What I usually do is run the "Raw Cycle" (Workers only), and once that's done, I run a bunch of review workers to update the existing collection, appending reviews data to it.

Your idea is better, because it serializes the process. We can have a worker running 24/7 and a crontab that will launch the ReviewWorker every 10-15 minutes, and it would hault after not finding newer apps to process the reviews for.

Is that what you thought ?

**Comment by seiyria** [comment]
That's basically what I thought. Alright, if that seems ok, I'll close this since there's a decent idea going there. Thanks!
